---
stages:
  - build
  - docker
  - acceptance

build:
  stage: build
  image: elixir:latest
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - _build
      - deps
  script:
    - mix local.rebar --force
    - mix local.hex --force
    - mix deps.get
    - mix compile --force --warnings-as-errors
    - mix format --check-formatted
    - mix credo --only warning

build_image:
  stage: docker
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u ${CI_REGISTRY_USER} -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build . -t ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:latest

acceptance:
  image: cabify/challenge:latest
  stage: acceptance
  only:
    - master
  variables:
    POSTGRES_URL: postgres://car_pooling:oAPEt2GcF4gh@ep-tight-silence-578941.ap-southeast-1.aws.neon.tech/car_pooling
    PORT: "9091"
  dependencies: []
  services:
    - name: ${CI_REGISTRY_IMAGE}:latest
      alias: pooling
  script:
    - /harness --address http://pooling:9091 acceptance
